FriggTest/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from FriggAnswer.views import question_view, upload_view, ajax_answer, custom_404


urlpatterns = [
    # Examples:
    # url(r'^$', 'FriggTest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'FriggAnswer/$', question_view, name='index'),
    #url(r'FriggAnswerFiles/$', upload_view),
    url(r'AnswerAjax/$', ajax_answer),
    #url(r'FriggResponse/$', bar),
    url(r'404',custom_404)
]

FriggAnswer/models.py
#/usr/bin/python
# coding: utf-8

from django.db import models

from inference import Search
from question import Question
from backend.backend_interface import *
from backend.utils import *
from messages import return_message, error_message
from backend.MongoUserInfo import MongoUser

question = Question()
inferencer = Search()
user = MongoUser()

def answer(perg):
    key = question.genKeyWords(perg)
    files = retrieve(key)
    if files is None:
        return u"Eu não tenho ideia!"
    else:
        data_title = retrieve_by_filename(key)
        res_t = inferencer.search(key, data_title)
        if res_t == 0:
            data_file = retrieve_equal_files(key)
            res_f = inferencer.search(key, data_file)
            if res_f == 0:
                data_commom = retrieve_commom(key)
                res_c = inferencer.search(key, data_commom)
                if res_c == 0:
                    return error_message()
                else:
                    user.insert(perg, len(res_c))
                    return return_data(res_c)
            else:
                user.insert(perg, len(res_f))
                return return_data(res_f)
        else:
            user.insert(perg, len(res_t))
            return return_data(res_t)


def answer_file(perg, file):
    if perg == "" or perg is None or len(perg) <=2:
        return u"Escreva algo para que eu possa responder!"
    key = question.genKeyWords(perg)
    arch = create_bag(file.read().decode('utf-8-sig'))
    res = inferencer.search_file(key, arch)
    return return_data_files(res)

def get_best_files(paragraphs):
    if len(paragraphs) == 1:
        return paragraphs
    elif len(set(paragraphs)) != len(paragraphs):
        para = [p for p in paragraphs if paragraphs.count(p) > 1]
        return list(set(para))
    else:
        return paragraphs

def return_data(result):
    message = u''+return_message()
    for r in result:
        message += "\n\n" +'<p>'+ r + '</p>'
    return message

def return_data_files(result):
    message = u''+return_message()
    message += "\n\n" + ' '.join(result)
    return message

FriggAnswer/forms.py
from django import forms

class FriggForm(forms.Form):
    question = forms.CharField(
        label='digite uma pergunta',
        max_length=55
    )

class UploadForm(forms.Form):
    file = forms.FileField(
        label="Escolha um arquivo",
        help_text="Max. 10kb"
    )

class FeedbackForm(forms.Form):
    opinion_text = forms.CharField(
        label='Conte-nos o que achou:',
        widget=forms.Textarea
    )
    feedback_text = forms.CharField(
        label='O que poderia ser melhor?',
        widget=forms.Textarea
    )
    CHOICES=[(1,'1'), (2,'2'), (3,'3'), (4,'4'), (5,'5')]

    rating = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

FriggAnswer/views.py
#/usr/bin/python
# coding: utf-8

from django.http import HttpResponse
from django.shortcuts import render_to_response, render
from django.template import RequestContext
from backend.MongoFeedback import MongoFeedback
import json

from .forms import FriggForm, UploadForm, FeedbackForm
from .models import answer, answer_file
from messages import intro_message

feedback = MongoFeedback()

def question_view(request):
    feed = FeedbackForm()
    ans = intro_message()
    form = FriggForm()
    context={"form": form, "intro": ans, "feedback": feed}
    return render_to_response("FriggTemplates/index.html", context ,RequestContext(request), RequestContext(request))

def ajax_answer(request):
    print 'vim até aqui'
    if request.method == 'POST':
        form = FriggForm(request.POST)
        #print 'segundo ponto de teste'
        if form.is_valid():
            quest = request.POST['question']
        ans = answer(quest)
        context={"answer": ans}
        return HttpResponse(
            json.dumps(context),
            content_type="application/json")

def custom_404(request):
    return render(request, 'FriggTemplates/404.html', {}, status=404)

def upload_view(request):
    ans = "Pode carregar o arquivo"
    if request.method == 'POST':
        up_form = UploadForm(request.POST, request.FILES)
        ques_form = FriggForm(request.POST)
        if up_form.is_valid() and ques_form.is_valid:
    	    text = request.FILES['file']
            ques = request.POST['question']
	    ans = answer_file(ques, text)
	    context={"up_form": up_form, "question_form":ques_form, "subtest": ans}
	    return render(request, "FriggTemplates/upload.html", context)
	    return HttpResponse("/FriggResponse/")
    #acontece de qualquer forma...
    up_form = UploadForm()
    ques = FriggForm()
    context={"up_form": up_form, "question_form":ques, "subtest": ans}
    return render_to_response("FriggTemplates/upload.html", context ,RequestContext(request), RequestContext(request))

FriggAnswer/templates/FriggTemplates/index.html
{% load staticfiles %}
<!DOCTYPE HTML>

<html lang='pt-br'>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/dialog.css' %}">
        <meta charset="utf-8">
        <link rel="shortcut icon" href="{% static 'imagens/favicon.ico'%}" type="image/x-icon">
        <link rel="icon" href="{% static 'imagens/favicon.ico'%}" type="image/x-icon">
        <title>Frigg</title>
    </head>
    <body>
<div id="all">
  <header>
  <img src="{% static 'imagens/logo.png' %}" alt="logo" id="logo">
  <div id="knot-border"></div>
  </header>
      <div id="main-img">
		<img id="frigg" src="{% static 'imagens/frigg-1.png' %}" alt="Deusa Frigg">
      </div>
	  <div id="rightside">
          <div id="intro">
                    {{intro}}
                </div>
      <div id="main-form">
           <form method="post" id="fquestion">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Perguntar!" id="grt_btn" class="peter-river-flat-button"/>
                </form>
      </div>
          <div id="ans">
                    {{answer|linebreaks}}
                </div>
          <!--p>O que você achou do sistema? tem alguma sugestão? <span id="feedback-input">Nos dê um feedback!</span-->
	</div>
	<footer>
        <p>Frigg Project</p>
        <p>Email: web-devs@outlook.com</p>
        <span></span>
	</footer>
	</div>
        <div id="success" title="Pensando...">
		<p>Espere um pouco, estou pensando na sua respsota.</p>
	</div>
       <link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
       <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
       <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
        <script>            
            $('#success').dialog({
                height: 80,
                width: 350,
                modal: true,
                resizable: false,
                dialogClass: 'no-close success-dialog',
                autoOpen: false,               
            });
            
            $(document).on('submit','#fquestion', function(e){
                if($('#id_question').val() == ''){
                     $('#ans').append('Escreva algo primeiro, para que eu possa responder!');
                }else{
                $('#success').dialog('open');
                e.preventDefault();
                $.ajax({
                    type:'POST',
                    url:'/AnswerAjax/',
                    data:{
                        question: $('#id_question').val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success: function(json){
                        $('#ans').html('');
                        $('#ans').append(json.answer);
                        $('#success').dialog('close');
                    },
                    error: function(){
                        $('#ans').html('');
                        $('#ans').html('Me parece que algo aqui não está certo.');
                        $('#success').dialog('close');
                    },
                }
                      );
                }
            });
        </script>
  </body>
</html>